### ISSUE TITLE
UI - When a user is updated, his display picture color changes

### ISSUE THREAD

**Issue by marvinchin** [CS2103AUG2017-W10-B2/main#109]

**Comment by KeithSOC** [comment]
After much considerations, I've decided to close this issue as I'm deeming it as a by-design, at least for now. Below were my thought-process.

Firstly, this has been the case for coloring of tab labels since AddressBook-Level4-v1 (https://github.com/nus-cs2103-AY1718S1/addressbook-level4/blob/master/docs/DeveloperGuide.adoc#improving-each-component). Implementation has been similar for coloring of profile photo thumbnails.

Secondly, the goal of the implementation has never aimed to ensure that the colors (of profile photo or tags) to remain the same for each person throughout every operation. Currently, exiting and re-entry of the application would trigger a different color for each person. The aim of the colors was to beef up the app's visual appeal.

Thirdly, a lack in priority. The real practical solution is a change of approach in implementation - randomly generate a color for a person at the point of adding, and store it as an additional field into the Person class. In this case, it would mimic say Telegram application's way of _permanently_ allocating the same colored profile photo thumbnail to a contact.

My two-cents! :)

**Comment by KeithSOC** [comment]
Re-opening as I've found a fix which will be in an upcoming PR.
